#!/bin/bash
cd     "${0%/*}"
source conf.bash
set    -e
shopt  -s        nullglob

if ! [[ $* =~ c ]]
then
    sudo xbps-install -y $REPOS
    sudo xbps-install -Syu
    sudo xbps-install -y $PACKAGES
    sudo gpasswd -a eetu _seatd

    git -C ~/src/void-packages pull || git clone https://github.com/void-linux/void-packages ~/src/void-packages
fi

if [[ $* =~ f ]]
then
    if ! [[ $* =~ c ]]
    then
        AMO_FILES=$(
            for N in $FIREFOX
            do
                curl -s https://addons.mozilla.org/api/v5/addons/addon/$N/ | jq -r .current_version.file.url &
            done
            wait
        )
        firefox $AMO_FILES 'about:preferences#search'
    fi

### CONFIG BEGIN ###

    for P in ~/.mozilla/firefox/*/
    do
        ln -sf ~/.mozilla/firefox/user.js $P
    done
fi

for U in ~/.local/share/Steam/userdata/*
do
    mkdir -p $U/730/local/cfg
    ln -sf ~/.local/share/Steam/steamapps/common/'Counter-Strike Global Offensive'/csgo/cfg/autoexec.cfg $U/730/local/cfg/
done

     rsync -rp home/ ~/ && source ~/.bash_profile
sudo rsync -rp root/  /
sudo grub-mkconfig -o /boot/grub/grub.cfg

for SV in $SERVICES
do
    sudo ln -sf /etc/sv/$SV /var/service/
done

[[ -f ~/.ssh/id_rsa ]] || ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa

for D in /mnt/{removable,sshfs}
do
    if ! mountpoint -q          $D
    then
        sudo mkdir  -p          $D
        sudo chown  $USER:$USER $D
    fi
done

### CONFIG END ###

if ! [[ $* =~ c ]]
then
    cd ~/src/void-packages
    ./xbps-src binary-bootstrap
    for P in $SRC
    do
        ./xbps-src -E pkg $P
    done
    xi -yu $SRC

    tput setaf 9
    xbps-query -m | rg -vFf <(echo $REPOS $PACKAGES $SRC | tr ' ' '\n') || true
    tput setaf 7
    
    rustup-init -y --no-modify-path
    cargo install $CARGO

    [[ -n $PIP ]] && pip install -U $PIP
    
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
