#!/bin/bash
set    -e
cd     "${0%/*}"
source conf.bash


### NOTE: dependencies ###
hash git rsync dconf aria2c rg || sudo apt install --yes git rsync dconf-cli aria2 ripgrep


### NOTE: config ###
for G in $GROUP
do
    sudo gpasswd -a $USER $G
done

     rsync -rlpt home/ ~/
sudo rsync -rlpt root/  /
source ~/.bash_profile

sudo udevadm control --reload-rules
sudo udevadm trigger

dconf load / <conf.dconf
[[ -f ~/.config/monitors.xml ]] && sudo cp ~/.config/monitors.xml /var/lib/gdm3/.config/

[[ $1 = "c" ]] && exit


### NOTE: download ###
mkdir -p ~/.cache/setup
cd       ~/.cache/setup

aria2c --continue --force-sequential --conditional-get --allow-overwrite $DEB $BIN $FONT

for VAR in DEB BIN FONT
do
    VAL=$(rg -or './$0' '[^ /]+(?: |$)' <<< ${!VAR})
    eval $VAR=\"$VAL\"
done


### NOTE: install ###
sudo dpkg --add-architecture i386
sudo apt install    --yes ca-certificates
sudo apt update
sudo apt install    --yes $APT
sudo apt install    --yes $APT_BACKPORTS -t bookworm-backports
sudo apt remove     --yes $APT_BLOCK
sudo apt-mark hold        $APT_BLOCK

sudo apt install --yes $DEB

sudo flatpak config --set languages "en;fi"
sudo flatpak install --system --assumeyes $FLATPAK

curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
cargo install $CARGO
rustup component add rust-analyzer

for G in $GO
do
    go install $G
done

for P in $PIPX
do
    pipx install $P
    I=PIPX_${P//-/_} I=${I^^} I=${!I}
    [[ -n $I ]] && pipx inject $P $I
done

mkdir -p bin
for B in $BIN
do
    case $(file --brief --mime-type $B) in
        application/x-executable) install --mode=755 $B ~/.local/bin;;
        application/?zip)         bsdtar xf $B -C bin;;
    esac
done
find  bin -type f -executable -exec mv {} ~/.local/bin \;
rm -r bin

cp $FONT ~/.local/share/fonts

sudo locale-gen --keep-existing

for E in $GNOME_EXTENSION
do
    if ! [[ -d ~/.local/share/gnome-shell/extensions/$E ]]
    then
        gdbus call --session                                                 \
            --dest         org.gnome.Shell.Extensions                        \
            --object-path /org/gnome/Shell/Extensions                        \
            --method       org.gnome.Shell.Extensions.InstallRemoteExtension \
            "$E"
    fi
done


### NOTE: update ###
sudo apt full-upgrade --yes
sudo flatpak update --system --assumeyes
pipx upgrade-all


### NOTE: clean ###
sudo apt autoremove --yes
sudo flatpak uninstall --system --assumeyes --unused

for S in $SERVICE_RESTART
do
    sudo systemctl restart $S
done
