#!/bin/bash

readarray -t D < <(bluetoothctl devices)
for I in ${!D[@]}
do
    M[$I]=$(cut -f2  -d' ' <<< ${D[$I]})
    N[$I]=$(cut -f3- -d' ' <<< ${D[$I]})
done

BT_CON() {
    C=0

    for I in ${!D[@]}
    do
        if [[ $(bluetoothctl info ${M[$I]}) =~ 'Connected: yes' ]]
        then
            if [[ $C -eq 0 ]]
            then
                echo -n 'BT: '
            else
                echo -n ', '
            fi
            echo -n "${N[$I]}"

            (( C += 1))
        fi
    done
    echo
}

i3status | while read LINE
do
    sed "s/BT/$(BT_CON)/g" <<< "$LINE"
done
