#!/bin/sh
SELECTION="$(tr '\0' ' ' < ~/.config/nnn/.selection)"
FILES="${SELECTION:-$1}"

for FILE in $FILES
do
    if [ -x "$FILE" ]
    then
        chmod -x "$FILE"
    else
        chmod +x "$FILE"
    fi
done
