nvenc_preset = 5
av1_mode = 1
channels = 2

resolutions = [
    960x544,
    1280x720,
    1920x1080
]

global_prep_cmd = [{
    "do":   "/home/eetu/src/monitors.sh stream",
    "undo": "/home/eetu/src/monitors.sh default"
}]
